development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tussam_development

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tussam_test

# set these environment variables on your prod server
production:
  sessions:
    default:
      hosts:
        - <%= ENV['MONGOID_HOST'] %>:27017
      port: <%= ENV['MONGOID_PORT'] %>
      username: <%= ENV['MONGOID_USERNAME'] %>
      password: <%= ENV['MONGOID_PASSWORD'] %>
      database: <%= ENV['MONGOID_DATABASE'] %>
      # slaves:
        #   - host: slave1.local
        #     port: 27018
        #   - host: slave2.local
        #     port: 27019
