development:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tussam_development

test:
  sessions:
    default:
      hosts:
        - localhost:27017
      database: tussam_test

# set these environment variables on your prod server
production:
  sessions:
    default:
<% if ENV['MONGOLAB_URI'] %>
      uri: <%= ENV['MONGOLAB_URI'] %>
<% else %>
      uri: mongodb://localhost:27017/tussam_development
<% end %>
