development:
  clients:
    default:
      hosts:
        - localhost:27017
      database: tussam_development

test:
  clients:
    default:
      hosts:
        - localhost:27017
      database: tussam_test

# set these environment variables on your prod server
production:
  clients:
    default:
<% if ENV['MONGOLAB_URI'] %>
      uri: <%= ENV['MONGOLAB_URI'] %>
<% else %>
      uri: mongodb://localhost:27017/tussam_development
<% end %>
      options:
        min_pool_size: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
        max_pool_size: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>
