# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5380a76fb1e13cd189851025dae6ed5bd13ee95f95e047f1137bdb3f5244050a5901451e648e81bedfb7c108ade061e8cf0e744e104fbe13448e44be52ddc40c

test:
  secret_key_base: 05cc035ccb45e5896184c8f08ae58b4142ff54f4694f7820fd430ad5de14d00f6fecacfb621255cbef8d3bd8ed5e26ebbc803c27eb87a8553ca4c6ec45e8e54d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
